#!/bin/sh

##### Aura Desktop Enviroment 1.2.1 #####

### KWIN WM ###
# kwin_x11 --replace &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

### OPENBOX WM ###
openbox-session &

## (optional) ##
# feh --bg-fill ~/.local/share/aurade/wallpaper.jpg &

## DO NOT REMOVE! ##
java -Dapp.name=AuraDE -jar "$HOME/.local/aurade/aurade.jar"
