#!/bin/sh

##### Aura Desktop Enviroment 1.2.1 #####

### KWIN WM (DO NOT USE CAUSE ITLL CAUSE PROBLEMS) ###

# sxhkd &
# bspwm &

### OPENBOX WM ###

openbox-session &

## (optional) ##
# feh --bg-fill ~/.local/share/aurade/wallpaper.jpg &

## DO NOT REMOVE! ##
java -Dapp.name=AuraDE -jar "$HOME/.local/aurade/aurade.jar"
